repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
        language_version: python3.8
        args: [--line-length=79, --target-version=py38]
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
      - id: flake8
        types: [ python ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --follow-imports, skip, --ignore-missing-imports]
